blogs/urls.py
from django.urls import path 
from .views import blog_list, book_detail, books_list


urlpatterns = [
    path('', blog_list, name='blog_list'),
    path('books', books_list, name='books_list'),
    path('books/<int:book_id>', book_detail, name='book_detail')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('', include('students.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

students/urls.py
from django.urls import path
from .views import student_list, student_detail, student_create, teacher_create, teacher_list, teacher_detail, student_update, student_delete, teachers_students

urlpatterns = [
	path('students', student_list, name='student_list'),
	path('student/update/<int:student_id>', student_update, name='student_update'),
	path('student_create', student_create, name='student_create'),
	path('student/<int:student_id>', student_detail, name='student_detail'),
	path('teachers', teacher_list, name='teacher_list'),
	path('teacher_create', teacher_create, name='teacher_create'),
	path('teacher/<int:teacher_id>', teacher_detail, name='teacher_detail'),
	path('student/delete/<int:student_id>', student_delete, name='student_delete'),
	path('teachers/students/<int:teacher_id>', teachers_students, name='teachers_students')
]
	

blogs/models.py
from django.db import models

# def book_cover_directory(instance, filename):
# 	return f"{settings.MEDIA_ROOT}/covers/{instance.title}/{filename}"

class Blog(models.Model):
	title = models.CharField(max_length=200)
	text = models.TextField()
	creation_date = models.DateField()

	def __str__(self):
		return self.title

class Book(models.Model):
	title = models.CharField(max_length=200, unique=True)
	description = models.TextField(null=False)
	release_date = models.DateField(auto_now_add=True)
	number_of_pages = models.PositiveIntegerField(null=True, blank=True)
	price = models.DecimalField(decimal_places=2, max_digits=6)
	in_stock = models.BooleanField(default=True)
	cover = models.ImageField(upload_to= 'covers')

	def __str__(self):
		return self.title

		
		

students/models.py
from django.db import models

class Teacher(models.Model):
	name = models.CharField(max_length=50)
	surname = models.CharField(max_length=100)
	subject = models.CharField(max_length=100)
	birth_date = models.DateField()
	school = models.CharField(max_length=150)
	photo = models.ImageField(upload_to= 'teacher_photo', null=True, blank=True)

	def __str__(self):
		return f"{self.name}: {self.subject}"


class Student(models.Model):
	name = models.CharField(max_length=50)
	surname = models.CharField(max_length=100)
	birth_date = models.DateField()
	school = models.CharField(max_length=150)
	grade= models.IntegerField()
	average_mark = models.DecimalField(max_digits=2, decimal_places=1)
	photo = models.ImageField(upload_to= 'students_photo', null=True, blank=True)
	teacher = models.ForeignKey(Teacher, null=True, on_delete=models.CASCADE, related_name = 'student')

	def __str__(self):
		return f"{self.name}: {self.grade}"

students/forms.py
from django import forms
from students.models import Student, Teacher


class StudentForm(forms.ModelForm):
    teacher = forms.ModelChoiceField(queryset=Teacher.objects.all(), empty_label="Выберите учителя из списка")
    class Meta:
        model = Student
        # fields = '__all__'
        fields = (
            'name', 'surname', 'birth_date', 'school', 'grade', 'average_mark', 'teacher','photo'
        )


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        # fields = '__all__'
        fields = (
            'name', 'surname', 'subject', 'birth_date', 'school'
        )

blogs/views.py
from django.shortcuts import render
from .models import Blog, Book

def blog_list(request):
	blog = Blog.objects.all() #Запрашиваем базу данных 
	context = {
		'blog': blog
	}
	
	return render(request, 'blogs/blog_list.html', context)

def books_list(request):
	books = Book.objects.all()
	context = {
		'books': books
	}
	return render(request, 'blogs/books_list.html', context)

def book_detail(request, book_id):
	# Получаем одну книгу из БД
	book = Book.objects.get(id = book_id)
	context = {
		'book': book
	}

	return render(request, 'blogs/book_detail.html', context)

students/views.py
import re
from django.shortcuts import get_object_or_404, redirect, render
from .models import Student, Teacher
from .forms import StudentForm, TeacherForm

def student_list(request,):
	students = Student.objects.all()
	# Берем значение поискового запроса
	search_query = request.GET.get('q', '')
	# ДОбавили 2 поисковик
	grade_query = request.GET.get('grade')
	teachers=Teacher.objects.all()
	if search_query:
		# Если был запрос то сделать фильтрацию.
		students = students.filter(name__contains=search_query)
		# Второй поисковик
	if grade_query:
		students = students.filter(grade=grade_query)

	context = {
		'students': students,
		'search_query': search_query,
		'teachers': teachers
	}

	return render(request, 'students/student_list.html', context)

def student_detail(request, student_id):
	# student = Student.objects.get(id=student_id)
	student = get_object_or_404(Student, id=student_id)
	context = {
		'student': student
	}

	return render(request, 'students/student_detail.html', context)

def	student_create(request):

	form = StudentForm(request.POST or None, files=request.FILES)
	if request.method == 'POST':
		if form.is_valid():
			form.save()
			return redirect('student_list')

	context = {'form': form}
	return render(request, 'students/student_create.html', context)

def student_update(request, student_id):
	student = get_object_or_404(Student, id=student_id)
	form = StudentForm(request.POST or None, instance=student)
	if request.method == 'POST':
		if form.is_valid:
			form.save()
			return redirect('student_list')
	context = {
		'form': form
	}
	return render(request, 'students/student_update.html', context)

def student_delete(request, student_id):
	# Берем ученика из БД
	student = get_object_or_404(Student, id=student_id)
	# Если запрос POST то удаляем и переотправляем на другую страницу
	if request.method == 'POST':
		student.delete()
		return redirect('student_list')
		# В ином случае рисуем страницу для подтверждения
	context = {
		'student': student
	}
	return render(request, 'students/student_delete.html', context)

def teacher_list(request):
	teachers = Teacher.objects.all()
	# Берем значение поискового запроса
	search_query = request.GET.get('q', '')
	# ДОбавили 2 поисковик
	grade_query = request.GET.get('subject')
	if search_query:
		# Если был запрос то сделать фильтрацию.
		teachers = teachers.filter(name__contains=search_query)
	context = {
		'teachers': teachers,
		'search_query': search_query
	}

	return render(request, 'students/teacher_list.html', context)


def teacher_detail(request, teacher_id):
	teacher = get_object_or_404(Teacher, id=teacher_id)
	students = teacher.student.all()
	context = {
		'students': students,
		'teacher': teacher
	}

	return render(request, 'students/teacher_detail.html', context)

def	teacher_create(request):
	form = TeacherForm(request.POST or None)
	if request.method == 'POST':
		if form.is_valid():
			form.save()
			return redirect(teacher_list)

	context = {'form': form}
	return render(request, 'students/teacher_create.html', context)

def teachers_students(request, teacher_id):
	students = Student.objects.filter(teacher_id=teacher_id)
	teachers = Teacher.objects.all()
	context = {
		'students': students,
		'teachers': teachers
	}

	return render(request, 'students/student_list.html', context)

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>{% block title %}Books{%endblock title %}</title>
		<link rel="stylesheet" type="text/css" href="{% static 'blogs/css/bootstrap.min.css' %}">
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Koulen&family=Montserrat:wght@500&display=swap" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{% static 'blogs/css/custom.css' %}">
	</head>
		<body>
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
			  	<div class="container-fluid">
			    	<a class="navbar-brand" href="#">
			    	<img width="25" height="25" src="{% static 'blogs/img/book.svg'%}" alt="">
			    	BOOKS Shop
					</a>
			    	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			      		<span class="navbar-toggler-icon"></span>
			    	</button>
			   		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			      		<ul class="navbar-nav me-auto mb-2 mb-lg-0">
			       			 <li class="nav-item dropdown">
			         			 <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
			           			 APPS
			          		</a>
			          	<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
			            	<li>
								<a class="dropdown-item" href="{% url 'books_list' %}">Все книги</a>
								<a class="dropdown-item" href="{% url 'student_list' %}">Все ученики</a>
								<a class="dropdown-item" href="{% url 'teacher_list' %}">Все учителя</a>
							</li>
			          	</ul>
			        		</li>
			    	</div>
			  	</div>
			</nav>
			<div class="container">
	
				{% block content %}
				{% endblock content %}
			</div>
			<script src="{% static 'blogs/js/bootstrap.bundle.min.js' %}"></script>

		</body>
</html>

templates/blogs/blog_list.html
{% extends "_base.html"%}     
{% block content %}
{% load static %}
	
	
	
{% endblock content %}

templates/blogs/book_detail.html
{% extends "_base.html"%}     
{% block content %}
{% load static %}
<div class="row mt-4">
    <img id="cover_img" src="{{book.cover.url}}">
    <div class="col-4">
        <h1>{{book.title}}</h1>
        <p>{{book.description}}</p>
        <p>Release date: {{book.release_date}}</p>
        <p>Price: {{book.price}} $.</p>
        <a href=""class="btn btn-primary">Заказать</a>
    </div>
        
</div>

    

{% endblock content %}

templates/blogs/books_list.html
{% extends "_base.html"%}     
{% block content %}
{% load static %}
<title>Books</title>
	<h1>Все книги</h1>
	<div class="row row-cols-6 row-cols-md-4 g-4">
		{% for b in books %}
			<div class=" col col-6">
					<div id="card" class="card">
						<img id="cover" class="card-img-top" src="{{b.cover.url}}" alt="Изображение не доступно">
						<div class="card-body">
							<h5 class="card-title">{{b.title}}</h5>
							<p class="card-text">{{b.description}}</p>
							<a href="{% url 'book_detail' b.id %}" class="btn btn-primary">Купить</a>
						</div>
					</div>
			</div>
		{% endfor %}
	</div>
	

{% endblock content %}

templates/students/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>{% block title %}Students{%endblock title %}</title>
		<link rel="stylesheet" type="text/css" href="{% static 'blogs/css/bootstrap.min.css' %}">
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Koulen&family=Montserrat:wght@500&display=swap" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{% static 'blogs/css/custom.css' %}">
	</head>
		<body>
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
			  <div class="container-fluid">
			    <a class="navbar-brand" href="#">STUDENTS</a>
			    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			      <span class="navbar-toggler-icon"></span>
			    </button>
			    <div class="collapse navbar-collapse" id="navbarSupportedContent">
			      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
			        <li class="nav-item">
			          <a class="nav-link active" aria-current="page" href="#">Home</a>
			        </li>
			        <li class="nav-item">
			          <a class="nav-link" href="#">Link</a>
			        </li>
			        <li class="nav-item dropdown">
			          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
			            Dropdown
			          </a>
			          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
			            <li><a class="dropdown-item" href="#">Action</a></li>
			            <li><a class="dropdown-item" href="#">Another action</a></li>
			            <li><hr class="dropdown-divider"></li>
			            <li><a class="dropdown-item" href="#">Something else here</a></li>
			          </ul>
			        </li>
			        <li class="nav-item">
			          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
			        </li>
			      </ul>
			      <form class="d-flex">
			        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
			        <button class="btn btn-outline-success" type="submit">Search</button>
			      </form>
			    </div>
			  </div>
			</nav>
			<div class="container">
	
				{% block content %}
				{% endblock content %}
			</div>
			<script src="{% static 'blogs/js/bootstrap.bundle.min.js' %}"></script>

		</body>
</html>

templates/students/student_create.html
{% extends '_base.html'%}
{% load widget_tweaks %}


{% block content %}
<h1>Создание профиля ученика</h1>
<div class="col-md-5">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_name">Введите имя:</label>
        {% render_field form.name class="form-control" placeholder="Имя"%}
        {% if form.name.errors%}
            <div class="alert alert-danger mt-3"  role="alert">
            
                <ul >
                    <li>
                        {{form.name.errors|striptags}}
                    </li>
                </ul>
            </div>
        {% endif %}
        <label for="id_surname">Введите фамилию:</label>
        {% render_field form.surname class="form-control" placeholder="Фамилия"%}
        {% if form.surname.errors%}
        <div class="alert alert-danger mt-3" role="alert">
        
            <ul>
                <li>
                    {{form.surname.errors|striptags}}
                </li>
            </ul>
        </div>
    {% endif %}
        <label for="id_birth_date">Дата рождения:</label>
         {% render_field form.birth_date class="form-control" type="date" %}
         {% if form.birth_date.errors%}
         <div class="alert alert-danger mt-3" role="alert">
         
             <ul>
                 <li>
                     {{form.birth_date.errors|striptags}}
                 </li>
             </ul>
         </div>
     {% endif %}
         <label for="id_school">школа:</label>
        {% render_field form.school class="form-control" placeholder="Школа"%}
        {% if form.school.errors%}
        <div class="alert alert-danger mt-3" role="alert">
        
            <ul>
                <li>
                    {{form.school.errors|striptags}}
                </li>
            </ul>
        </div>
    {% endif %}
        <label for="id_grade">класс:</label>
        {% render_field form.grade class="form-control" placeholder="Класс"%}
        {% if form.grade.errors%}
        <div class="alert alert-danger mt-3" role="alert">
        
            <ul>
                <li>
                    {{form.grade.errors|striptags}}
                </li>
            </ul>
        </div>
    {% endif %}
        <label for="id_average_mark">средняя оценка:</label>
         {% render_field form.average_mark class="form-control" placeholder="Оценка"%}
         {% if form.average_mark.errors%}
         <div class="alert alert-danger mt-3" role="alert">
         
             <ul>
                 <li>
                     {{form.average_mark.errors|striptags}}
                 </li>
             </ul>
         </div>
     {% endif %}
         <label for="id_photo">Фото:</label>
         {% render_field form.photo class="form-control" placeholder=" Добавить фото"%} 
         {% if form.photo.errors%}
         <div class="alert alert-danger mt-3" role="alert">
         
             <ul>
                 <li>
                     {{form.photo.errors|striptags}}
                 </li>
             </ul>
         </div>
     {% endif %}
        <label for="id_teacher">учитель:</label>
        {% render_field form.teacher class="form-control"%}
        {% if form.teacher.errors%}
        <div class="alert alert-danger mt-3" role="alert">
        
            <ul>
                <li>
                    {{form.teacher.errors|striptags}}
                </li>
            </ul>
        </div>
    {% endif %}
        <button
            type="submit"
            class="btn btn-success mt-3" >добавить
        </button>
    </form>
</div>
{% endblock content %}

templates/students/student_delete.html
{% extends "_base.html"%}     

{% block title %}Удаление{%endblock title %}

{% block content %}
    <h3>Вы действительно хотите удалить ученика </h3> 
    <h1>"{{student.name}}"</h1> 
    <form action="" method="POST" encytype="multipart/form-data">
        {% csrf_token%} {{form.as_p}}
        <button type="submit" class="btn btn-primary">Удалить</button>
        <a class="btn btn-warning" href="{% url 'student_list' %}">Отменить</a>
    </form>
    

{% endblock content %}

templates/students/student_detail.html
{% extends "_base.html"%}     
{% block content %}
{% load static %}
<div class="row mt-4">
    <img id="cover_img" src="{{student.photo.url}}">
    <div class="col-4">
        <h3>ФИО: {{student.surname}} {{student.name}}</h3>
        <p>Дата рождения: {{student.birth_date}}</p>
        <p>Номер школы: {{student.school}}</p>
        <p>Класс: {{student.grade}}</p>
        <p>Ср. оценка: {{student.average_mark}}</p>

    </div>
        
</div>






{% endblock content %}

templates/students/student_list.html
{% extends "_base.html"%}     
{% block content %}
	<div class="row mt-4">
		<h3 class="text-center">Cписок учеников</h3>
		<!-- для того что бы работал поиск нужно добавить в конце  action=""-->
		<form class="row row-cols-lg-auto g-3 align-items-center" action="">
			<div class="col-md-6 col-12">
			 	 <label class="visually-hidden" for="inlineFormInputGroupUsername">Имя</label>
				  <!-- Чтобы добавить поиск нужно добавить после  placeholder="Имя ученика" 
					name="q" value="{{search_query}}" required minlength=3> -->
				<input type="text" class="form-control" id="inlineFormInputGroupUsername" placeholder="Имя ученика"
				name="q" value="{{search_query}}">
				<!-- required minlength=3 -->
				
			</div>
			<!-- Добавить доп. строку поиска -->
			<div class="col-md-2 col-12">
				<label class="visually-hidden" for="gradeInput">класс:</label>
				<input class="form-control" type="number" name="grade" min="1" max="11" id="gradeInput">
			</div>
		  	<div class="col-md-2 col-12">
			  	<button type="submit" class="btn btn-primary">Поиск</button>
			</div>
			<div class="col-12">Показать всех
				<a href="{% url 'student_create' %}">Добавить</a>
			</div>
		</form>
		<table class="table table-striped">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">имя</th>
					<th scope="col">Фамилия</th>
					<th scope="col">школа</th>
				</tr>
			</thead>
			<tbody>
				{% for s in students%}
					<tr>
						<th scope="row">{{s.id}}</th>
						<td>
							<a href="{% url 'student_detail' s.id %}">{{s.name}}</a>
						</td>
						<td>{{s.surname}}</td>
						<td>{{s.school}}</td>
						<td>
							<a href="{% url 'student_update' s.id %}">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" 
								fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
								<path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 
								5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 
								2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 
								.5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 
								7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5
								 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5
								  0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
							  	</svg>

							</a>
							<a href="{% url 'student_delete' s.id %}">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" 
								fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
								<path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 
								1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 
								1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 
								0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5
								.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
								</svg>
							</a>
						</td>
					</tr>
					<!--для того что бы показать что пользователя не существует! -->
				{% empty %}
					<tr>
						<td colspan="4" class="text-center">Поиск не дал результатов</td>
					</tr>	
				{% endfor %}
			</tbody>
		</table>
		<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
			<a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
			  <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
			  <span class="fs-4">Список учителей</span>
			</a>
			<hr>
			<ul class="nav nav-pills flex-column mb-auto">
			  {% for t in teachers %}
			  <li class="nav-item">
				<a href="{% url 'teachers_students' t.id %}">{{t.name}}</a>
			  </li>
			{% endfor %}

			</ul>
			<hr>
			<div class="dropdown">
			  <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
				<img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
				<strong>mdo</strong>
			  </a>
			  <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
				<li><a class="dropdown-item" href="#">New project...</a></li>
				<li><a class="dropdown-item" href="#">Settings</a></li>
				<li><a class="dropdown-item" href="#">Profile</a></li>
				<li><hr class="dropdown-divider"></li>
				<li><a class="dropdown-item" href="#">Sign out</a></li>
			  </ul>
			</div>
		  </div>
	</div>




{% endblock content %}

templates/students/student_update.html
{% extends "_base.html"%}     

{% block title %}Редактирование{%endblock title %}

{% block content %}
    <h3>
        Редактирование
    </h3>  
    <form action="" method="POST" encytype="multipart/form-data">
        {% csrf_token%} {{form.as_p}}
        <button type="submit" class="btn btn-primary">Обновить</button>
    </form>
    

{% endblock content %}

templates/students/teacher_create.html
{% extends '_base.html'%}
{% load widget_tweaks %}
{% block content %}
<div class="col-md-5">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label>Введите имя:</label>
            {% render_field form.name class="form-control"%}
        <label >Введите фамилию:</label>
            {% render_field form.surname class="form-control"%}
        <label >Введите фамилию:</label>
        {% render_field form.birth_date class="form-control"%}
        <button
            type="submit"
            class="btn btn-success">Добавить
        </button>

    </form>
</div>

{% endblock content %}

templates/students/teacher_detail.html
{% extends "_base.html"%}     
{% block content %}
{% load static %}
<div class="row mt-4">
    <img id="cover_img" src="{{teacher.photo.url}}">
    <div class="col-4">
        <h3>ФИО: {{teacher.surname}} {{teacher.name}}</h3>
        <p>Дата рождения: {{teacher.birth_date}}</p>
        <p>Номер школы: {{teacher.school}}</p>
        <p>Предмет: {{teacher.subject}}</p>
        <h4>Список студентов</h4>
        {% for student in students %}
           <a href="{% url 'student_detail' student.id %}"><h5>{{student.name}}</h5></a> 
        {% endfor %}
    </div>
        
</div>






{% endblock content %}

templates/students/teacher_list.html
{% extends "_base.html"%}     
{% block content %}
	<div class="row mt-4">
		<h3 class="text-center">список учителей</h3>
		<!-- для того что бы работал поиск нужно добавить в конце  action=""-->
		<form class="row row-cols-lg-auto g-3 align-items-center" action="">
			<div class="col-md-6 col-12">
			 	 <label class="visually-hidden" for="inlineFormInputGroupUsername">Имя</label>
				  <!-- Чтобы добавить поиск нужно добавить после  placeholder="Имя ученика" 
					name="q" value="{{search_query}}" required minlength=3> -->
				<input type="text" class="form-control" id="inlineFormInputGroupUsername" placeholder="Имя учителя"
				name="q" value="{{search_query}}">
				<!-- required minlength=3 -->
				
			</div>
			<!-- Добавить доп. строку поиска -->
		  	<div class="col-md-2 col-12">
			  	<button type="submit" class="btn btn-primary">Поиск</button>
			</div>
			<div class="col-12">Показать всех
				<a href="{% url 'teacher_create' %}">Добавить</a>
			</div>
		</form>
		<table class="table table-striped">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">имя</th>
					<th scope="col">Фамилия</th>
					<th scope="col">школа</th>
				</tr>
			</thead>
			<tbody>
				{% for t in teachers %}
					<tr>
						<th scope="row">{{t.id}}</th>
						<td>
							<a href="{% url 'teacher_detail' t.id %}">{{t.name}}</a>
						</td>
						<td>{{t.surname}}</td>
						<td>{{t.school}}</td>
					</tr>
					<!--для того что бы показать что пользователя не существует! -->
				{% empty %}
					<tr>
						<td colspan="4" class="text-center">Поиск не дал результатов</td>
					</tr>	
				{% endfor %}
			</tbody>
		</table>
	</div>




{% endblock content %}